on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      # Étape 1 : Récupération du code
      - uses: actions/checkout@v3
      
      # Étape 2 : Installation des dépendances système
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libopencv-dev libglib2.0-0 libsm6 libxrender1 libxext6

      # Étape 3 : Configuration de Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Étape 4 : Installation des dépendances Python
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Étape 5 : Analyse de linting avec Flake8
      - name: flake8 Lint
        uses: py-actions/flake8@v2

      # Étape 6 : Exécution des tests avec Pytest
      - name: Test with pytest
        run: |
          pytest
